# Generated by Django 4.1.5 on 2023-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_cartitems_cartitem_client_alter_cart_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/static/products/img'),
        ),
    ]
