# Generated by Django 4.1.5 on 2023-01-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_cart_client_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
