# Generated by Django 4.1.5 on 2023-01-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_variation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
