# Generated by Django 4.1.5 on 2023-01-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/static/products/img/'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='image',
            field=models.ImageField(upload_to='products/static/products/img/'),
        ),
    ]
